[package]
name = "gneiss-ntrip"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio = { version = "1.37", features = ["full"] }
reqwest = { version = "0.12", features = ["stream"] }
base64 = "0.22"
futures-util = "0.3"
url = "2.5"
tracing = "0.1"
bytes = "1.5"
