//! CSRS-PPP Output Trajectory Parser.
//!
//! Parses output files generated by Natural Resources Canada's Canadian Spatial
//! Reference System (CSRS-PPP) online engine (format: `.pos`).

use std::io::BufRead;
use nalgebra::Vector3;
use gneiss_core::time::GpsTime;

/// A single solution epoch parsed from a CSRS-PPP `.pos` file.
#[derive(Debug, Clone, PartialEq)]
pub struct CsrsEpoch {
    /// GPS time of the epoch
    pub time: GpsTime,
    /// Geodetic latitude in degrees
    pub lat_deg: f64,
    /// Geodetic longitude in degrees
    pub lon_deg: f64,
    /// Ellipsoidal height in meters
    pub height_m: f64,
    /// Quality flag (e.g. 6 = PPP float)
    pub quality: u32,
    /// Earth-Centered, Earth-Fixed (ECEF) coordinates in meters
    pub pos_ecef: Vector3<f64>,
}

fn parse_date(s: &str) -> Result<(i32, i32, i32), String> {
    let parts: Vec<&str> = s.split('/').collect();
    if parts.len() != 3 {
        return Err(format!("invalid date format: {}", s));
    }
    let y = parts[0].parse::<i32>().map_err(|e| e.to_string())?;
    let m = parts[1].parse::<i32>().map_err(|e| e.to_string())?;
    let d = parts[2].parse::<i32>().map_err(|e| e.to_string())?;
    Ok((y, m, d))
}

fn parse_time(s: &str) -> Result<(i32, i32, f64), String> {
    let parts: Vec<&str> = s.split(':').collect();
    if parts.len() != 3 {
        return Err(format!("invalid time format: {}", s));
    }
    let hr = parts[0].parse::<i32>().map_err(|e| e.to_string())?;
    let min = parts[1].parse::<i32>().map_err(|e| e.to_string())?;
    let sec = parts[2].parse::<f64>().map_err(|e| e.to_string())?;
    Ok((hr, min, sec))
}

fn parse_coordinates(parts: &[&str]) -> Result<(f64, f64, f64, u32), String> {
    if parts.len() < 6 {
        return Err("insufficient columns".to_string());
    }
    let lat = parts[2].parse::<f64>().map_err(|e| e.to_string())?;
    let lon = parts[3].parse::<f64>().map_err(|e| e.to_string())?;
    let h = parts[4].parse::<f64>().map_err(|e| e.to_string())?;
    let q = parts[5].parse::<u32>().map_err(|e| e.to_string())?;
    Ok((lat, lon, h, q))
}

/// Parse a single line from a CSRS-PPP `.pos` file.
pub fn parse_csrs_line(line: &str) -> Option<CsrsEpoch> {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with('%') {
        return None;
    }
    let parts: Vec<&str> = trimmed.split_whitespace().collect();
    if parts.len() < 6 {
        return None;
    }
    let (y, m, d) = parse_date(parts[0]).ok()?;
    let (hr, min, sec) = parse_time(parts[1]).ok()?;
    let (lat, lon, h, q) = parse_coordinates(&parts).ok()?;
    let gps_time = GpsTime::from_calendar(y, m, d, hr, min, sec);
    let llh = Vector3::new(lat.to_radians(), lon.to_radians(), h);
    let pos_ecef = gneiss_core::coords::llh_to_ecef(llh);
    Some(CsrsEpoch { time: gps_time, lat_deg: lat, lon_deg: lon, height_m: h, quality: q, pos_ecef })
}

/// Parse all epochs from a CSRS-PPP `.pos` reader.
pub fn parse_csrs_pos<R: BufRead>(reader: R) -> Result<Vec<CsrsEpoch>, String> {
    let mut epochs = Vec::new();
    for (line_idx, line_res) in reader.lines().enumerate() {
        let line = line_res.map_err(|e| format!("read error line {}: {}", line_idx, e))?;
        if let Some(epoch) = parse_csrs_line(&line) {
            epochs.push(epoch);
        }
    }
    Ok(epochs)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    #[test]
    fn test_parse_csrs_single_line() {
        let line = "2020/12/24 21:28:42.023999 40.097029227777774 -105.14726476944445 1577.3571 6 0";
        let ep = parse_csrs_line(line).expect("must parse valid CSRS line");
        assert_eq!(ep.quality, 6);
        assert!((ep.lat_deg - 40.0970292).abs() < 1e-6);
        assert!((ep.lon_deg - (-105.1472648)).abs() < 1e-6);
        assert!((ep.height_m - 1577.3571).abs() < 1e-4);
        assert!(ep.pos_ecef.norm() > 6.0e6);
    }

    #[test]
    fn test_parse_csrs_header_ignored() {
        let header = "%%  GPST                  latitude(deg) longitude(deg)  height(m)       Q  ns";
        assert!(parse_csrs_line(header).is_none());
        assert!(parse_csrs_line("").is_none());
    }

    #[test]
    fn test_parse_csrs_reader() {
        let data = "%% header\n2020/12/24 21:28:42.000 40.0 -105.0 1500.0 6 0\n2020/12/24 21:28:43.000 40.0 -105.0 1500.0 6 0\n";
        let epochs = parse_csrs_pos(Cursor::new(data)).expect("parse csrs data");
        assert_eq!(epochs.len(), 2);
    }
}
